[theme]
base = "light"
primaryColor = "#A100FF"
backgroundColor = "#F4F5F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F0F14"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
